jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: build wheels
        uses: PyO3/maturin-action@v1
        with:
          args: '--release --out dist --locked'
          manylinux: auto
          sccache: true
          target: x86_64
      - name: upload wheels
        uses: actions/upload-artifact@v6
        with:
          name: wheels-linux-x86_64
          path: dist
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
      - name: build wheels
        uses: PyO3/maturin-action@v1
        with:
          args: '--release --out dist --locked'
          sccache: true
          target: aarch64
      - name: upload wheels
        uses: actions/upload-artifact@v6
        with:
          name: wheels-macos-aarch64
          path: dist
  release:
    if: github.ref == 'refs/heads/main'
    name: publish
    needs:
      - linux
      - macos
      - sdist
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v7
        with:
          merge-multiple: true
          path: dist
      - name: install uv
        uses: astral-sh/setup-uv@v7
      - name: publish to pypi
        run: uv publish --trusted-publishing always --skip-existing dist/*
  sdist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: build sdist
        uses: PyO3/maturin-action@v1
        with:
          args: '--out dist'
          command: sdist
      - name: upload sdist
        uses: actions/upload-artifact@v6
        with:
          name: wheels-sdist
          path: dist
name: pypi
'on':
  workflow_dispatch: {}
permissions:
  contents: read
